### ISSUE TITLE
fix: npm run deploy process hangs after build

### ISSUE THREAD

**Issue by QuintyHH** [marianzburlea/pug-starter#66]
using the latest version with the patched build script, the **run deploy** stills stalls after build finishes, however, if the process is manually killed to continue, it returns `TypeError: dest.on is not a function
    at Transform.Readable.pipe (_stream_readable.js:662:8)
    at pipe (C:\Users\user\JSApps\blog-samp\gulp/deploy.js:25:8)
    at taskWrapper (C:\Users\user\JSApps\blog-samp\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:415:14)
    at runBound (domain.js:428:12)
    at asyncRunner (C:\Users\user\JSApps\blog-samp\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:82:9)` 

need confirmation, as it might be a local problem

**Comment by QuintyHH** [comment]
![image](https://user-images.githubusercontent.com/42803595/59882111-ffb81e00-93b9-11e9-889e-a902b500aa8b.png)

**Comment by QuintyHH** [comment]
[This](https://github.com/QuintyHH/blog-samp) is the project that wont deploy
